<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.272">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Normal AI - Training and fine-tuning models</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../existing-models.html" rel="next">
<link href="../intro/models.html" rel="prev">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>


<link rel="stylesheet" href="../static/style.css">
<meta property="og:title" content="Normal AI - Training and fine-tuning models">
<meta property="og:description" content="Taking your data to school">
<meta property="og:image" content="https://normalai.org/intro/assets/conveyor.png">
<meta property="og:site-name" content="Normal AI">
<meta name="twitter:title" content="Normal AI - Training and fine-tuning models">
<meta name="twitter:description" content="Taking your data to school">
<meta name="twitter:image" content="https://normalai.org/intro/assets/conveyor.png">
<meta name="twitter:creator" content="@dangerscarf">
<meta name="twitter:card" content="summary_large_image">
</head>

<body class="nav-sidebar docked nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">Normal AI</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link active" href="../intro/index.html" rel="" target="" aria-current="page">
 <span class="menu-text">Intro</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../text/index.html" rel="" target="">
 <span class="menu-text">Text</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../images/index.html" rel="" target="">
 <span class="menu-text">Images</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../audio/index.html" rel="" target="">
 <span class="menu-text">Audio</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../video/index.html" rel="" target="">
 <span class="menu-text">Video</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../diy/index.html" rel="" target="">
 <span class="menu-text">Custom</span></a>
  </li>  
</ul>
            <div class="quarto-navbar-tools ms-auto">
</div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
      <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../intro/index.html">Introduction</a></li><li class="breadcrumb-item"><a href="../intro/fine-tune-model.html">Training a model</a></li></ol></nav>
      <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
      </a>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal sidebar-navigation docked overflow-auto">
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Home</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true">
 <span class="menu-text">Introduction</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../intro/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Welcome</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../intro/models.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">What is a model?</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../intro/fine-tune-model.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">Training a model</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true">
 <span class="menu-text">Existing models</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../existing-models.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">How to use</span></a>
  </div>
</li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="false">
 <span class="menu-text">📝 Text</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../text/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Text models overview</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../text/text-classification.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Classifying</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../text/named-entity-recognition.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Extracting people and organizations</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../text/document-similarity.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Document similarity</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../text/asking-pdfs-questions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Asking PDFs questions</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../text/asking-documents-questions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Asking documents questions</span></a>
  </div>
</li>
      </ul>
  </li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="false">
 <span class="menu-text">🖼️ Images</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../images/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Image models overview</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../images/image-classification.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Classifying</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../images/vqa.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Asking questions</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../images/instance-segmentation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Counting things</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../images/semantic-segmentation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Measuring amounts</span></a>
  </div>
</li>
      </ul>
  </li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" aria-expanded="false">
 <span class="menu-text">🔊 Audio</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../audio/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Audio models overview</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../audio/transcription.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Transcription</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../audio/removing-noise.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Noise removal</span></a>
  </div>
</li>
      </ul>
  </li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" aria-expanded="false">
 <span class="menu-text">🎬 Video</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../video/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Video models overview</span></a>
  </div>
</li>
      </ul>
  </li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" aria-expanded="true">
 <span class="menu-text">Build your own</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-7" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../diy/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Customization overview</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../diy/text-classification.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Text classifier</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../diy/image-classification.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Image classifier</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../diy/research.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Exploring the possibilities</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../diy/custom.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Custom tools</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#how-training-works" id="toc-how-training-works" class="nav-link active" data-scroll-target="#how-training-works">How training works</a>
  <ul class="collapse">
  <li><a href="#the-olden-days-of-machine-learning" id="toc-the-olden-days-of-machine-learning" class="nav-link" data-scroll-target="#the-olden-days-of-machine-learning">The olden days of machine learning</a></li>
  <li><a href="#fine-tuning-models" id="toc-fine-tuning-models" class="nav-link" data-scroll-target="#fine-tuning-models">Fine tuning models</a></li>
  </ul></li>
  <li><a href="#lets-fine-tune-a-model" id="toc-lets-fine-tune-a-model" class="nav-link" data-scroll-target="#lets-fine-tune-a-model">Let’s fine-tune a model!</a>
  <ul class="collapse">
  <li><a href="#the-problem" id="toc-the-problem" class="nav-link" data-scroll-target="#the-problem">The problem</a></li>
  <li><a href="#create-our-model" id="toc-create-our-model" class="nav-link" data-scroll-target="#create-our-model">Create our model</a></li>
  <li><a href="#using-our-model" id="toc-using-our-model" class="nav-link" data-scroll-target="#using-our-model">Using our model</a></li>
  <li><a href="#try-it-out" id="toc-try-it-out" class="nav-link" data-scroll-target="#try-it-out">Try it out</a></li>
  </ul></li>
  </ul>
<div class="toc-actions"><div><i class="bi bi-github"></i></div><div class="action-links"><p><a href="https://github.com/jsoma/normal-ai/edit/main/intro/fine-tune-model.qmd" class="toc-action">Edit this page</a></p><p><a href="https://github.com/jsoma/normal-ai/issues/new" class="toc-action">Report an issue</a></p></div></div></nav>
    </div>
<!-- main -->
<main class="content page-columns page-full" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default page-columns page-full">
    
    <div class="quarto-title-banner page-columns page-full">
      <div class="quarto-title column-body">
        <h1 class="title">Training and fine-tuning models</h1>
                <p class="subtitle lead">Taking your data to school</p>
                              </div>
    </div>
      
    
    <div class="quarto-title-meta">

        
      
        
      </div>
      
    
    </header>
  

<p>Before a model can make any decisions for you, it needs to be trained on <em>how</em> to make those decisions.</p>
<p>As we talked about in <a href="../intro/models.html">the last section</a>, there are two approaches to teaching your model:</p>
<ol type="1">
<li><strong>Training</strong> a model from scratch</li>
<li>Taking a model that already knows something (words, shapes, etc) and <strong>fine-tuning it</strong></li>
</ol>
<p>We’ll start by looking at how people <em>used</em> to do it, and now look at the insanely simple drag-and-drop ways you can do it nowadaays.</p>
<section id="how-training-works" class="level2">
<h2 class="anchored" data-anchor-id="how-training-works">How training works</h2>
<section id="the-olden-days-of-machine-learning" class="level3">
<h3 class="anchored" data-anchor-id="the-olden-days-of-machine-learning">The olden days of machine learning</h3>
<p>Back in the good old days of <a href="https://investigate.ai/">writing fun investigative machine learning algorithms</a>, fine-tuning models was out of reach: you’d pretty much always plan out an algorithm yourself to <a href="https://www.latimes.com/local/cityhall/la-me-crime-stats-side-20151015-story.html">dig through documents</a> or <a href="https://open.nytimes.com/how-the-new-york-times-uses-software-to-recognize-members-of-congress-29b46dd426c7">recognize members of Congress</a>.</p>
<p>You’d have to make decisions like: what kind of algorithm are we using? The algorithm is the baseline of our model, and determines exactly how it works. Maybe we’d use a <strong>random forest</strong>? Maybe <strong>naive Bayes</strong> or a <strong>support vector machine</strong>? You might not know the difference, but you’d notice when know one did a better job than the other!</p>
<div class="callout-info">
<p>Speaking honestly, you’d probably just try them all and use the one that performed the best, not really caring about the <em>why</em>.</p>
</div>
<p>Beyond picking the fundamentals of your model, you’d also need to make decisions about how your data was pre-processed before it was tossed in. You might make decisions like:</p>
<ul>
<li>Would you remove accents like coöperation and café?</li>
<li>Would you standardized <em>fish</em>, <em>fishes</em>, and <em>fishing</em> to count as the same word?</li>
<li>Should you keep your image in color or is greyscale going to work better?</li>
</ul>
<p>While these sorts of choices can certainly play a role in building a model in the current world, <em>you rarely have to do that any more.</em> We’ve been freed from it!</p>
<div class="callout-info">
<p>Before we get too far, I just want to say <strong>I love traditional machine learning models.</strong> Knowing what’s going into the system, making a million little tweaks, and feature-engineering your way to high heaven is a great thing.</p>
<p>And as a secret bonus, <em>traditional machine learning will oftentimes surpass AI-driven models with a heck of a lot less computational work.</em></p>
<p>The problem is all those tiny little decisions require technical know-how that raise the barrier to entry to these skills. The approach we take below will often reach 90% of the way there with 2% of the effort!</p>
</div>
</section>
<section id="fine-tuning-models" class="level3">
<h3 class="anchored" data-anchor-id="fine-tuning-models">Fine tuning models</h3>
<p>As we explained in the <a href="../intro/models.html">last section</a>, training a model from scratch is like teaching a baby to speak. What if we could instead <strong>build from a base that was a little bit more advanced?</strong></p>
<p>Maybe we could start with something that knows a little bit of English or French, maybe it understands what a circle is or what a tree looks like. All we’d need is to give it a little guidance oh how to use those skills for <em>our</em> problem, instead of home-schooling it into adulthood.</p>
<p>This is the process of <strong>fine-tuning</strong>, and it’s how the majority of AI and machine learning is done these days. Megacorps like Facebook, Google and Microsoft have shoveled the contents of the internet into gigantic, powerful models, burning an incredible amount of money, time, and electricity to train them in ways that we could never think of doing on our home computer.</p>
<p>These models know <em>all kinds of things</em>, and by leveraging them we’ve skipped past starting with a baby and gone to a fully-functioning adult!</p>
<div class="callout callout-style-simple callout-warning">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<p>This is probably the right place to say: yes, this is one of the reasons bias exists in these models. Being a fully-functioning adult doesn’t necessarily mean you’re always right, or your ideas make sense!</p>
</div>
</div>
</div>
<p>To fine-tune the model, you show the model examples of what you want it to do. It can be practically anything:</p>
<ul>
<li>Positive tweets vs negative tweets</li>
<li>Pieces of legislature about the environment vs healthcare vs taxes vs policing</li>
<li>Slides with tumors vs no tumors</li>
<li>Photos with a box drawn around every single tree</li>
</ul>
<p>Thanks to the beauty of machine learning, the model leverages its existing abilities to learn how to complete your task. Whether it’s categorizing documents or scoring tumors, <em>that’s it!</em></p>
<p>Not all models are available for fine-tuning, though.</p>
<ul>
<li>Some models are held by the companies that produce them. They write papers about them but don’t release <em>anything</em>.</li>
<li>Other models are held by the companies that produce them, but are available for fine-tuning through some sort of “give us money and we’ll give you access” interface</li>
<li>Still other models exist freely on the internet, able to be downloaded and fine-tuned</li>
</ul>
<p>We’re mostly concerned with the last bit here. And the best place to find those models is <a href="https://huggingface.co/models">Hugging Face</a>.</p>
</section>
</section>
<section id="lets-fine-tune-a-model" class="level2">
<h2 class="anchored" data-anchor-id="lets-fine-tune-a-model">Let’s fine-tune a model!</h2>
<p>We’re going to reproduce the research that’s (partially) behind Texty’s <a href="https://texty.org.ua/d/2018/amber_eng/">Leprosy of the land</a> piece on illegal amber mines in Ukraine.</p>
<p><a href="https://github.com/texty/amber-methodology/blob/master/doc/rarcticle.pdf">From their description of the project</a>:</p>
<blockquote class="blockquote">
<p>Increased world prices for amber led to illegal mining for this gemstone in North Western part of Ukraine. The total area of region with close-to-surface deposits of amber is about 70,000 km<sup>2</sup>. Number of images with good enough resolution needed to cover this area is about 450,000. To process such amount of information we developed XGBoost and ResNet based classifier, trained it with initial ground-truth images with traces of amber mining and created most complete interactive map of this phenomena as of time of publishing in March, 2018 [1].</p>
</blockquote>
<p>You can find <a href="https://github.com/texty/amber-methodology">their methodology here</a>, a <a href="https://github.com/texty/amber-methodology/blob/master/doc/c%2Bj2019.md">simpler writeup here</a>, or a reproducible walkthrough on Google’s infrastructure from <a href="https://newsinitiative.withgoogle.com/resources/lessons/how-you-can-use-machine-learning/">Google News Initiative</a>.</p>
<p>Our goal is to <strong>quickly fine-tune a model to reproduce the story</strong>. You’re going to be <em>shocked</em> at how easy it is.</p>
<section id="the-problem" class="level3">
<h3 class="anchored" data-anchor-id="the-problem">The problem</h3>
<p>With a collection of satellite imagery, we need to find pictures like those below.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../assets/amber/example.png" class="quarto-discovered-preview-image img-fluid figure-img"></p>
<p></p><figcaption class="figure-caption">Example of amber mines</figcaption><p></p>
</figure>
</div>
<p>See those little round things? <strong>Those are illegal amber mines.</strong> While we could spend nights and weekends scrolling through image after image looking for those little round bits, a computer is going to do a much better job of it. Specifically speaking, a <em>fine-tuned computer vision model</em> is going to do a better job of it.</p>
<p>Feel free to <a href="../assets/amber/amber-smaller.zip">download the images here</a>. It’s a subset of the much larger selection of well over a thousand images that the Google News Initiative course used.</p>
</section>
<section id="create-our-model" class="level3">
<h3 class="anchored" data-anchor-id="create-our-model">Create our model</h3>
<p>We’re going to head on over to <a href="https://ui.autotrain.huggingface.co/projects">Hugging Face’s AutoTrainer</a>, a tool to allow users to easily fine-tune existing models. Once you’re there, create an account and log in.</p>
<div class="callout callout-style-simple callout-warning">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<p>We’re doing this using Hugging Face, but there are a million tools that you can use to automatically train or fine-tune models out there. Hugging Face is a great place to do it because it’s a platform <em>dedicated to models</em>. Unlike something like Google’s model-training tool, Hugging Face has a ton of infrastructure around it to allow you to test and use the model in a lot of convenient (and social!) ways.</p>
<p>Also: why are we using a tool instead of coding? Because the whole point of this is <strong>it doesn’t matter how the model is made.</strong> It’s fine that it’s a black box, it’s fine that we don’t know what’s going on under the surface or where it came from, what matters is focusing on <em>how we use it.</em> Being able to design a model from scratch in PyTorch or whatever doesn’t prevent you from being irresponsible with it!</p>
</div>
</div>
</div>
<section id="create-a-project" class="level4">
<h4 class="anchored" data-anchor-id="create-a-project">Create a project</h4>
<p>After you’re logged in, click the <strong>New Project</strong> button.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../assets/amber/new-project-click.png" class="img-fluid figure-img"></p>
<p></p><figcaption class="figure-caption">Create a new project</figcaption><p></p>
</figure>
</div>
<p>Create a new project, selecting <strong>Image Classification</strong> since we’re attempting to put images into categories. If we were attempting to classify tweets, we’d click <strong>Text</strong> and then one of the <strong>Text Classification</strong> options.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../assets/amber/new-project-fill.png" class="img-fluid figure-img"></p>
<p></p><figcaption class="figure-caption">Enter in the details</figcaption><p></p>
</figure>
</div>
<p>An important part of this screen is the <strong>Model choice</strong> option. Do you know anything about the different models we could fine-tune for this project? Are those “XGBoost” and “ResNet” things mentioned above by Texty relavant? Does RoBERTa from the last section speak images?</p>
<p>You don’t have to worry, because <strong>Hugging Face knows we don’t know, so it just picks for us.</strong> In the same way that traditional machine learning meant running a few different algorithms to see which one worked best - SVM vs logistic regression vs random forest – Hugging Face will pit a few contenders against each other and let us pick which one we feel performed the best!</p>
</section>
<section id="uploading-our-data" class="level4">
<h4 class="anchored" data-anchor-id="uploading-our-data">Uploading our data</h4>
<p>After you’ve created the new project, you’ll drag the <a href="../assets/amber/amber-smaller.zip">two folders of images</a> into the drop zone. There are 250 images in each folder because Hugging Face allows us to train on 500 images for free, and keeping a balance between yes/no amber mines lets the model get a good idea of what each category looks like.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../assets/amber/upload-1.png" class="img-fluid figure-img"></p>
<p></p><figcaption class="figure-caption">Upload your images</figcaption><p></p>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../assets/amber/upload-2.png" class="img-fluid figure-img"></p>
<p></p><figcaption class="figure-caption">Done uploading</figcaption><p></p>
</figure>
</div>
<p>That’s your data prep! Once it’s done uploading you can click the <strong>go to trainings</strong> button.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../assets/amber/go-to-training.png" class="img-fluid figure-img"></p>
<p></p><figcaption class="figure-caption">Go to training</figcaption><p></p>
</figure>
</div>
</section>
<section id="training-our-models" class="level4">
<h4 class="anchored" data-anchor-id="training-our-models">Training our models</h4>
<p>AutoTrain now gives us a few options on what we want to do: we’re fine trying out 5 different models (expanding that probably won’t change much), and we’re just within the 500-image limit.</p>
<div class="callout-danger">
<p>As much as I love it, Hugging Face is <em>super expensive</em> if you’re going over the limit. In that case I would recommend <a href="https://huggingface.co/docs/transformers/notebooks">fine-tuning on Google Colab instead</a>. It isn’t too bad if you know how to work with Python!</p>
</div>
<p>If we were training a model from scratch instead of fine-tuning, 500 images might not be enough! But thanks to the fact that we’re standing on the shoulders of an existing model that knows about shapes and colors, we should be ok. <strong>Start that training!</strong></p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../assets/amber/press-train.png" class="img-fluid figure-img"></p>
<p></p><figcaption class="figure-caption">Models finished fine-tuning</figcaption><p></p>
</figure>
</div>
<p>Wait a bit – have fun watching the models compete – and soon you’ll have five fine-tuned models all ready for you.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../assets/amber/models-done-training.png" class="img-fluid figure-img"></p>
<p></p><figcaption class="figure-caption">Models finished fine-tuning</figcaption><p></p>
</figure>
</div>
</section>
<section id="evaluating-model-performance" class="level4">
<h4 class="anchored" data-anchor-id="evaluating-model-performance">Evaluating model performance</h4>
<p>Many of our models scored 95%, how exciting! But when we click through to the model, we get a <strong>lot more numbers to pay attention to.</strong></p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../assets/amber/model-page.png" class="img-fluid figure-img"></p>
<p></p><figcaption class="figure-caption">Model performance</figcaption><p></p>
</figure>
</div>
<p>I’m going to give you the numbers for a few of the models below:</p>
<table class="table">
<thead>
<tr class="header">
<th>name</th>
<th>welcome-panther</th>
<th>poised-zebra</th>
<th>fast-wasp</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Model base</td>
<td>beit</td>
<td>vit</td>
<td>swin</td>
</tr>
<tr class="even">
<td>Loss</td>
<td>0.073</td>
<td>0.195</td>
<td>0.144</td>
</tr>
<tr class="odd">
<td>Accuracy</td>
<td>0.950</td>
<td>0.950</td>
<td>0.950</td>
</tr>
<tr class="even">
<td>Precision</td>
<td>0.979</td>
<td>0.941</td>
<td>0.979</td>
</tr>
<tr class="odd">
<td>Recall</td>
<td>0.92</td>
<td>0.960</td>
<td>0.920</td>
</tr>
<tr class="even">
<td>AUC</td>
<td>0.999</td>
<td>0.984</td>
<td>0.989</td>
</tr>
<tr class="odd">
<td>F1</td>
<td>0.948</td>
<td>0.950</td>
<td>0.948</td>
</tr>
</tbody>
</table>
<p>The big reason <strong>accuracy</strong> might not be important is if you have “imbalanced” data. Let’s say we had 90 images of no mines and 10 images of mines. I could guess <em>not a mine</em> every single time and still come away with a 90% accuracy score! We need some way to punish certain kinds of wrong guesses.</p>
<p><strong>Precision</strong> and <strong>recall</strong> are measures that talk specifically about the ways the model’s predictions can be wrong. The somewhat technical explanation:</p>
<ul>
<li>Higher precision means fewer false positives, i.e.. fewer times a non-mine is classified as a mine.</li>
<li>Higher recall means fewer false negatives, i.e.&nbsp;fewer times a mine is classified as a non-mine.</li>
</ul>
<p>Or, alternatively:</p>
<ul>
<li>High precision means “if I say YES it’s a mine, it’s definitely a mine.” Low precision means “if I say YES it’s a mine… maybe it isn’t.”</li>
<li>High recall means “I guessed most of the mines,” while low recall means “I missed some of the mines.”</li>
</ul>
<p><a href="https://uberpython.wordpress.com/2012/01/01/precision-recall-sensitivity-and-specificity/">This page has a great decription of how tests can “cheat” and get misleading high scores</a>, I highly recommend giving it a read (mostly the last third or so). But to get to the point:</p>
<p>While all of our models have an accuracy of 95%, <code>welcome-panther</code> has a higher precision and lower recall, while <code>poised-zebra</code> has a lower precision and higher recall. <strong>Which metric one is better?</strong></p>
<p>In our situation, we’ll be manually reviewing the mines and <strong>we don’t want to miss any amber mines</strong>. It’s better for us to have a non-mine categorized as a mine (we’ll remove it) instead of a mine categorized as a non-mine (we’ll never notice it). As a result, we want a <strong>higher recall</strong> – it might give us false positives, but we’ll deal with it.</p>
<p>We could also use the <strong>F1 score</strong>, which attempts to be a holistic store that balances all types of misclassifications. In this case our pick of <code>poised-zebra</code> with a score of <code>0.950</code> slightly beats out <code>welcome-panther</code>’s score of <code>0.948</code>, so it agrees with our decision!</p>
</section>
</section>
<section id="using-our-model" class="level3">
<h3 class="anchored" data-anchor-id="using-our-model">Using our model</h3>
<p>Next I use the settings page to rename and move our model. Now that I’ve made it publish, you can find it at <a href="https://huggingface.co/wendys-llc/amber-mines">wendys-llc/amber-mines</a> You might want to keep yours private, but I wanted you to be able to give mine a try!</p>
<p><img src="../assets/amber/rename.png" class="img-fluid"></p>
<p>Now I’ll deploy the model as a Gradio app for some nice fun playing around.</p>
<p><img src="../assets/amber/app-1.png" class="img-fluid"></p>
<p><img src="../assets/amber/app-2.png" class="img-fluid"></p>
<p><img src="../assets/amber/app-3.png" class="img-fluid"></p>
<p>And then we’re done!</p>
</section>
<section id="try-it-out" class="level3">
<h3 class="anchored" data-anchor-id="try-it-out">Try it out</h3>
<p>You can find <a href="https://huggingface.co/spaces/wendys-llc/wendys-llc-amber-mines">the finished app here</a> and try it out below.</p>
<p>Am I cheating by using examples that it was trained on? <em>Absolutely,</em> but you get the idea.</p>
<script type="module" src="https://gradio.s3-us-west-2.amazonaws.com/3.22.1/gradio.js"></script>
<p><gradio-app src="https://wendys-llc-wendys-llc-amber-mines.hf.space"></gradio-app></p>
<p>Were you to actually want to use this for <em>real</em>, I would recommend taking a look at the <a href="https://huggingface.co/course/chapter1/1">Hugging Face course</a></p>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../intro/models.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text">What is a model?</span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../existing-models.html" class="pagination-link">
        <span class="nav-page-text">How to use</span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">Find me at <a href="mailto:jonathan.soma@gmail.com">jonathan.soma@gmail.com</a> or <a href="https://twitter.com/dangerscarf"><span class="citation" data-cites="dangerscarf">@dangerscarf</span></a></div>   
    <div class="nav-footer-center">©2023, Jonathan Soma</div>
    <div class="nav-footer-right">
      <ul class="footer-items list-unstyled">
    <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/jsoma">
      <i class="bi bi-github" role="img">
</i> 
    </a>
  </li>  
    <li class="nav-item compact">
    <a class="nav-link" href="https://twitter.com/dangerscarf">
      <i class="bi bi-twitter" role="img">
</i> 
    </a>
  </li>  
    <li class="nav-item compact">
    <a class="nav-link" href="mailto:jonathan.soma@gmail.com">
      <i class="bi bi-envelope" role="img">
</i> 
    </a>
  </li>  
</ul>
    </div>
  </div>
</footer>



</body></html>